### ISSUE TITLE
no implicit conversion of Fixnum into String

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#175]
When trying to edit a .tint.yml file with the following contents, we get a TypeError exception.

``` yml
options:
  colours:
    red: Rouge
    blue: Bleu
    white: Blanc
  numbers:
    - 0
    - 1
    - 2
    - 3
    - 10
  pastas:
    spa: Spaghetti
    pen: Penne
    rot: Rotini
    bar: Barbina
    cap: Capellini
    fus: Fusilli
```
